"""Tests for core.video_extract.

Synthetic videos are generated by FFmpeg's ``lavfi`` color source so
the suite has zero binary fixtures and runs anywhere FFmpeg is. Each
generated video is ~10 KB and renders in <500 ms; the whole module
adds maybe 3-4 seconds to the suite.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from PIL import Image

from core.video_extract import (
    VideoMetadata,
    _make_test_video,
    export_clip,
    extract_frame,
    probe_video,
)


@pytest.fixture
def red_video(tmp_path: Path) -> Path:
    """1-second 320x240 red @ 30fps. Reused across the simpler tests
    so we only pay the FFmpeg-spawn cost once when pytest reuses the
    fixture cache (per-test in this case, but cheap)."""
    return _make_test_video(tmp_path / "red.mp4")


def test_probe_returns_metadata(red_video: Path):
    meta = probe_video(red_video)
    assert isinstance(meta, VideoMetadata)
    assert meta.width == 320
    assert meta.height == 240
    # Allow a tiny margin around 1000ms — FFmpeg may round at the
    # boundary depending on the encoder's GOP alignment.
    assert 800 <= meta.duration_ms <= 1200
    assert meta.codec == "h264"
    assert 28 <= meta.fps <= 32


def test_probe_missing_file_raises(tmp_path: Path):
    with pytest.raises(FileNotFoundError):
        probe_video(tmp_path / "nope.mp4")


def test_probe_unreadable_file_raises(tmp_path: Path):
    """A 0-byte file with .mp4 extension. FFmpeg should fail to
    parse it; we expect a RuntimeError, not a silent zero-result."""
    bogus = tmp_path / "garbage.mp4"
    bogus.write_bytes(b"")
    with pytest.raises(RuntimeError):
        probe_video(bogus)


def test_extract_frame_writes_jpeg(red_video: Path, tmp_path: Path):
    out = tmp_path / "frame.jpg"
    written = extract_frame(red_video, position_ms=500, output_path=out)
    assert written == out
    assert out.exists()
    # Round-trip: should be a valid JPEG sized like the source video
    img = Image.open(out)
    assert img.size == (320, 240)


def test_extract_frame_creates_parent_dirs(red_video: Path, tmp_path: Path):
    out = tmp_path / "deep" / "nested" / "frame.jpg"
    extract_frame(red_video, position_ms=100, output_path=out)
    assert out.exists()


def test_extract_frame_missing_video_raises(tmp_path: Path):
    with pytest.raises(FileNotFoundError):
        extract_frame(
            tmp_path / "nope.mp4", 0, tmp_path / "out.jpg",
        )


def test_export_clip_produces_shorter_video(red_video: Path, tmp_path: Path):
    out = tmp_path / "clip.mp4"
    export_clip(
        red_video, start_ms=200, end_ms=700, output_path=out,
    )
    assert out.exists()
    meta = probe_video(out)
    # 500ms requested; allow encoder boundary slack.
    assert 350 <= meta.duration_ms <= 650


def test_export_clip_applies_crop(red_video: Path, tmp_path: Path):
    """Crop a 320x240 source down to a centered 160x120 region.
    Verifies the ``-vf crop=`` flag actually flowed through."""
    out = tmp_path / "cropped.mp4"
    export_clip(
        red_video, start_ms=0, end_ms=500, output_path=out,
        crop_pixels=(80, 60, 160, 120),
    )
    meta = probe_video(out)
    assert meta.width == 160
    assert meta.height == 120


def test_export_clip_invalid_range_raises(red_video: Path, tmp_path: Path):
    with pytest.raises(ValueError):
        export_clip(red_video, 500, 200, tmp_path / "x.mp4")
    with pytest.raises(ValueError):
        export_clip(red_video, 100, 100, tmp_path / "x.mp4")


def test_export_clip_invalid_crop_raises(red_video: Path, tmp_path: Path):
    with pytest.raises(ValueError):
        export_clip(
            red_video, 0, 500, tmp_path / "x.mp4",
            crop_pixels=(0, 0, 0, 100),
        )


def test_export_clip_rotation_90_swaps_dimensions(
    red_video: Path, tmp_path: Path,
):
    """Source is 320x240; a 90° rotation must produce a 240x320
    output. Verifies the ``transpose`` filter actually flows
    through the FFmpeg chain."""
    out = tmp_path / "rotated_cw.mp4"
    export_clip(
        red_video, start_ms=0, end_ms=500, output_path=out,
        rotation_degrees=90,
    )
    meta = probe_video(out)
    assert meta.width == 240
    assert meta.height == 320


def test_export_clip_rotation_180_preserves_dimensions(
    red_video: Path, tmp_path: Path,
):
    out = tmp_path / "rotated_180.mp4"
    export_clip(
        red_video, start_ms=0, end_ms=500, output_path=out,
        rotation_degrees=180,
    )
    meta = probe_video(out)
    assert meta.width == 320
    assert meta.height == 240


def test_export_clip_rotation_invalid_raises(red_video: Path, tmp_path: Path):
    with pytest.raises(ValueError):
        export_clip(
            red_video, 0, 500, tmp_path / "x.mp4",
            rotation_degrees=45,
        )


def test_export_clip_missing_video_raises(tmp_path: Path):
    with pytest.raises(FileNotFoundError):
        export_clip(
            tmp_path / "nope.mp4", 0, 1000, tmp_path / "out.mp4",
        )


def test_export_clip_include_audio_off_succeeds(red_video: Path, tmp_path: Path):
    """``include_audio=False`` must not break the export pipeline.
    Our synthetic video has no audio anyway, but the FFmpeg command
    needs to handle the ``-an`` flag without warning the user about
    a missing audio stream."""
    out = tmp_path / "muted.mp4"
    export_clip(
        red_video, start_ms=0, end_ms=400, output_path=out,
        include_audio=False,
    )
    assert out.exists()
