"""Fitted Looks calibration data — GENERATED, do not edit.

Generated by ``python -m tools.calibrate_looks export`` from
run ``2026-06-10_054129`` (fitted 2026-06-10T06:16:52).
Regenerate after any refit (spec/54 §5). The router + cluster
constants are the A-layer; LOOK_BIASES are the B-layer
(spec/54 §3).  Keys in LOOK_BIASES are INTERNAL identifiers —
display names + final vocabulary belong to the UI slice
(spec/54 §7).
"""

FEATURE_KEYS = ("p50", "p25", "p99", "p1", "spread")

ROUTER = {
    'general': {
        "zscore_mean": (0.401499, 0.263795, 0.919279, 0.054346, 0.689446),
        "zscore_std": (0.132434, 0.101936, 0.065371, 0.048926, 0.092349),
        "centroids": (
            (-0.001681, 0.013388, 0.617975, -0.586806, 0.726813),
            (0.002185, -0.017405, -0.803367, 0.762847, -0.944857),
        ),
        "clusters": (
            {'exposure_target': 0.465625, 'exposure_max_ev': 0.1175, 'exposure_highlight_ceiling': 0.99, 'whites_p99_target': 0.98, 'whites_gain': 214.375, 'blacks_p1_target': 0.07, 'blacks_gain': 60.0, 'shadows_p25_threshold': 0.3875, 'shadows_gain': 120.0, 'shadows_max': 34.875, 'highlights_p75_threshold': 0.795, 'highlights_gain': 120.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.65, 'contrast_gain': 40.0, 'contrast_max': 15.0},
            {'exposure_target': 0.499375, 'exposure_max_ev': 0.2175, 'exposure_highlight_ceiling': 0.99, 'whites_p99_target': 0.98, 'whites_gain': 146.875, 'blacks_p1_target': 0.012813, 'blacks_gain': 55.0, 'shadows_p25_threshold': 0.205, 'shadows_gain': 215.0, 'shadows_max': 25.125, 'highlights_p75_threshold': 0.75, 'highlights_gain': 120.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.66125, 'contrast_gain': 86.875, 'contrast_max': 15.0},
        ),
    },
    'landscape': {
        "zscore_mean": (0.443739, 0.325326, 0.85312, 0.126815, 0.603503),
        "zscore_std": (0.142911, 0.151076, 0.11413, 0.100298, 0.116306),
        "centroids": (
            (-0.508919, -0.672064, -0.270701, -0.719477, 0.478036),
            (0.626361, 0.827156, 0.33317, 0.88551, -0.588352),
        ),
        "clusters": (
            {'exposure_target': 0.55, 'exposure_max_ev': 0.2825, 'exposure_highlight_ceiling': 0.864, 'whites_p99_target': 0.98, 'whites_gain': 70.625, 'blacks_p1_target': 0.11875, 'blacks_gain': 0.0, 'shadows_p25_threshold': 0.15, 'shadows_gain': 640.0, 'shadows_max': 23.375, 'highlights_p75_threshold': 0.795, 'highlights_gain': 400.0, 'highlights_max': 60.0, 'contrast_compression_threshold': 0.38, 'contrast_gain': 30.0, 'contrast_max': 50.0},
            {'exposure_target': 0.47125, 'exposure_max_ev': 0.24375, 'exposure_highlight_ceiling': 0.8545, 'whites_p99_target': 0.950313, 'whites_gain': 182.5, 'blacks_p1_target': 0.0, 'blacks_gain': 52.5, 'shadows_p25_threshold': 0.25, 'shadows_gain': 120.0, 'shadows_max': 12.0, 'highlights_p75_threshold': 0.885, 'highlights_gain': 120.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.9, 'contrast_gain': 109.375, 'contrast_max': 27.375},
        ),
    },
    'macro': {
        "zscore_mean": (0.358822, 0.214872, 0.82154, 0.039533, 0.621835),
        "zscore_std": (0.172163, 0.156204, 0.091924, 0.053009, 0.131131),
        "centroids": (
            (-0.832727, -0.73037, -0.780986, -0.403302, -0.396511),
            (0.351624, 0.14904, 0.710868, -0.173757, 0.705643),
            (0.94282, 1.377456, -0.432262, 1.645172, -1.410353),
        ),
        "clusters": (
            {'exposure_target': 0.345625, 'exposure_max_ev': 0.1, 'exposure_highlight_ceiling': 0.94, 'whites_p99_target': 0.904313, 'whites_gain': 89.375, 'blacks_p1_target': 0.085, 'blacks_gain': 200.0, 'shadows_p25_threshold': 0.33, 'shadows_gain': 400.0, 'shadows_max': 13.125, 'highlights_p75_threshold': 0.75, 'highlights_gain': 400.0, 'highlights_max': 80.0, 'contrast_compression_threshold': 0.4175, 'contrast_gain': 86.25, 'contrast_max': 50.0},
            {'exposure_target': 0.50875, 'exposure_max_ev': 0.17, 'exposure_highlight_ceiling': 0.888937, 'whites_p99_target': 0.8885, 'whites_gain': 0.0, 'blacks_p1_target': 0.084062, 'blacks_gain': 292.5, 'shadows_p25_threshold': 0.265, 'shadows_gain': 290.0, 'shadows_max': 10.5, 'highlights_p75_threshold': 0.66, 'highlights_gain': 400.0, 'highlights_max': 6.25, 'contrast_compression_threshold': 0.47, 'contrast_gain': 40.0, 'contrast_max': 15.0},
            {'exposure_target': 0.535, 'exposure_max_ev': 0.10875, 'exposure_highlight_ceiling': 0.865188, 'whites_p99_target': 0.872688, 'whites_gain': 12.5, 'blacks_p1_target': 0.11875, 'blacks_gain': 187.5, 'shadows_p25_threshold': 0.365, 'shadows_gain': 665.0, 'shadows_max': 9.75, 'highlights_p75_threshold': 0.9075, 'highlights_gain': 320.0, 'highlights_max': 80.0, 'contrast_compression_threshold': 0.3425, 'contrast_gain': 144.375, 'contrast_max': 50.0},
        ),
    },
    'portrait': {
        "zscore_mean": (0.317539, 0.162963, 0.914939, 0.038047, 0.764403),
        "zscore_std": (0.129885, 0.094938, 0.088508, 0.030216, 0.116816),
        "centroids": (
            (-0.646879, -0.748694, -0.655564, -0.611096, -0.477296),
            (0.618754, 0.716142, 0.627061, 0.584527, 0.456544),
        ),
        "clusters": (
            {'exposure_target': 0.469375, 'exposure_max_ev': 0.13, 'exposure_highlight_ceiling': 0.959, 'whites_p99_target': 0.833875, 'whites_gain': 145.0, 'blacks_p1_target': 0.055, 'blacks_gain': 60.0, 'shadows_p25_threshold': 0.2825, 'shadows_gain': 120.0, 'shadows_max': 27.0, 'highlights_p75_threshold': 0.5, 'highlights_gain': 585.0, 'highlights_max': 23.75, 'contrast_compression_threshold': 0.5, 'contrast_gain': 81.25, 'contrast_max': 15.0},
            {'exposure_target': 0.47875, 'exposure_max_ev': 0.10875, 'exposure_highlight_ceiling': 0.936562, 'whites_p99_target': 0.98, 'whites_gain': 267.5, 'blacks_p1_target': 0.068125, 'blacks_gain': 25.0, 'shadows_p25_threshold': 0.24, 'shadows_gain': 635.0, 'shadows_max': 10.75, 'highlights_p75_threshold': 0.752812, 'highlights_gain': 740.0, 'highlights_max': 60.0, 'contrast_compression_threshold': 0.81125, 'contrast_gain': 161.25, 'contrast_max': 50.0},
        ),
    },
    'selfie': {
        "zscore_mean": (0.500913, 0.312454, 0.945149, 0.062219, 0.743577),
        "zscore_std": (0.101903, 0.07253, 0.042905, 0.031756, 0.09292),
        "centroids": (
            (0.7381, 0.746723, 0.165323, 0.356797, -0.054361),
            (-1.014888, -1.026745, -0.227318, -0.490596, 0.074747),
        ),
        "clusters": (
            {'exposure_target': 0.47875, 'exposure_max_ev': 0.1, 'exposure_highlight_ceiling': 0.94, 'whites_p99_target': 0.98, 'whites_gain': 47.5, 'blacks_p1_target': 0.016563, 'blacks_gain': 80.0, 'shadows_p25_threshold': 0.4425, 'shadows_gain': 185.0, 'shadows_max': 10.875, 'highlights_p75_threshold': 0.885, 'highlights_gain': 0.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.9, 'contrast_gain': 214.375, 'contrast_max': 24.375},
            {'exposure_target': 0.454375, 'exposure_max_ev': 0.2, 'exposure_highlight_ceiling': 0.88775, 'whites_p99_target': 0.98, 'whites_gain': 66.25, 'blacks_p1_target': 0.0, 'blacks_gain': 87.5, 'shadows_p25_threshold': 0.3525, 'shadows_gain': 125.0, 'shadows_max': 11.25, 'highlights_p75_threshold': 0.75, 'highlights_gain': 120.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.9, 'contrast_gain': 184.375, 'contrast_max': 11.625},
        ),
    },
    'wildlife': {
        "zscore_mean": (0.457471, 0.325776, 0.869294, 0.071622, 0.61122),
        "zscore_std": (0.178392, 0.176565, 0.096836, 0.067505, 0.144788),
        "centroids": (
            (-0.162265, -0.086174, -1.202267, 0.043998, -0.766208),
            (1.230114, 1.282746, 0.343027, 1.183505, -0.481214),
            (-0.48125, -0.550464, 0.543333, -0.580199, 0.674113),
        ),
        "clusters": (
            {'exposure_target': 0.505, 'exposure_max_ev': 0.1, 'exposure_highlight_ceiling': 0.834313, 'whites_p99_target': 0.970438, 'whites_gain': 70.0, 'blacks_p1_target': 0.085, 'blacks_gain': 105.0, 'shadows_p25_threshold': 0.3225, 'shadows_gain': 110.0, 'shadows_max': 10.875, 'highlights_p75_threshold': 0.685312, 'highlights_gain': 345.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.545, 'contrast_gain': 53.125, 'contrast_max': 16.5},
            {'exposure_target': 0.544375, 'exposure_max_ev': 0.17375, 'exposure_highlight_ceiling': 0.922187, 'whites_p99_target': 0.967062, 'whites_gain': 30.625, 'blacks_p1_target': 0.042188, 'blacks_gain': 142.5, 'shadows_p25_threshold': 0.25, 'shadows_gain': 120.0, 'shadows_max': 12.0, 'highlights_p75_threshold': 0.885, 'highlights_gain': 0.0, 'highlights_max': 20.0, 'contrast_compression_threshold': 0.87125, 'contrast_gain': 107.5, 'contrast_max': 22.125},
            {'exposure_target': 0.529375, 'exposure_max_ev': 0.12625, 'exposure_highlight_ceiling': 0.829562, 'whites_p99_target': 0.976187, 'whites_gain': 51.875, 'blacks_p1_target': 0.089687, 'blacks_gain': 192.5, 'shadows_p25_threshold': 0.2675, 'shadows_gain': 275.0, 'shadows_max': 20.25, 'highlights_p75_threshold': 0.885, 'highlights_gain': 240.0, 'highlights_max': 60.0, 'contrast_compression_threshold': 0.38, 'contrast_gain': 30.0, 'contrast_max': 50.0},
        ),
    },
}

# Look biases (spec/54 §3.4 — v1, Nelson-accepted 2026-06-10).
LOOK_BIASES = {
    'brighter': {'exposure': 0.18, 'contrast': -4.0, 'shadows': 8.0, 'whites': 6.0, 'vibrance': 8.0},
    'deeper': {'exposure': -0.15, 'contrast': 10.0, 'highlights': -5.0, 'blacks': -10.0, 'vibrance': 10.0},
}

# Creative-filter recipes (spec/55 — the locked nine, v0 recipes Nelson-approved 2026-06-10).
# Shape: key -> {'base': recipe, 'by_style': {style: recipe}} (FilterRecipe.from_dict).
FILTER_RECIPES = {
    'vivid': {
        "base": {'params': {'saturation': 18.0, 'vibrance': 20.0, 'contrast': 8.0}},
    },
    'bw': {
        "base": {'bw_mix': (0.42, 0.4, 0.18), 'params': {'contrast': 15.0}},
    },
    'sepia': {
        "base": {'bw_mix': (0.38, 0.42, 0.2), 'tint': (1.08, 1.0, 0.82), 'params': {'contrast': 6.0}, 'fade': 0.04},
    },
    'faded': {
        "base": {'params': {'saturation': -25.0, 'contrast': -8.0}, 'fade': 0.1, 'tint': (1.02, 1.0, 0.96)},
    },
    'golden': {
        "base": {'tint': (1.1, 1.02, 0.86), 'split_highlights': (1.06, 1.0, 0.92), 'params': {'contrast': -4.0, 'vibrance': 6.0}},
    },
    'cinema': {
        "base": {'split_shadows': (0.92, 1.0, 1.12), 'split_highlights': (1.08, 1.02, 0.92), 'params': {'saturation': -15.0, 'contrast': 6.0}},
    },
    'bleach': {
        "base": {'params': {'saturation': -55.0, 'contrast': 22.0, 'exposure': -0.05}},
    },
    'dramatic': {
        "base": {'clarity': 0.55, 'params': {'contrast': 10.0, 'saturation': -8.0, 'highlights': -20.0}},
    },
    'crisp': {
        "base": {'clarity': 0.35, 'vignette': 0.18, 'params': {'vibrance': 15.0, 'blacks': -8.0}},
        "by_style": {
            'macro': {'clarity': 0.4, 'vignette': 0.22, 'params': {'vibrance': 18.0, 'blacks': -16.0}},
            'wildlife': {'clarity': 0.4, 'vignette': 0.15, 'tint': (1.04, 1.0, 0.94), 'params': {'vibrance': 14.0, 'blacks': -6.0}},
        },
    },
    # spec/116 — four new creative filters built from the engine
    # primitives. Each ships a single coherent effect (the new
    # component's strength) plus a small supporting move where it
    # serves the look. AF-point anchoring is handled at the call
    # sites — the recipe doesn't carry a centre.
    'subject_pop': {
        "base": {'spotlight': 0.6, 'spotlight_radius': 0.55},
    },
    'dehaze': {
        "base": {'dehaze': 0.5, 'params': {'contrast': 4.0}},
    },
    'dreamy_glow': {
        "base": {'glow': 0.5, 'fade': 0.06, 'params': {'saturation': -8.0}},
    },
    'film_grain': {
        "base": {'grain': 0.5, 'params': {'contrast': 6.0, 'saturation': -10.0}},
    },
    # spec/118 — specular-hotspot tamer. Defaults to subject-only so
    # background sparkles + rim lights survive the recovery.
    'deglare': {
        "base": {'deglare': 0.5, 'deglare_subject_only': True},
    },
}
